#!/usr/bin/env bash
#Transfer a file from client to server

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY "
	exit 1
fi
# Set variables
path_to_file=$1
username=$3
ip=$2
ssh_key_path=$4

# Disabling strict host key check
scp -o "StrictHostKeyChecking=no" -i "$ssh_key_path" "$path_to_file" "$username@$ip:/"  

# Checking to see if the file was sent

if [ $? -eq 0 ]
then
	echo "FILE wasSuccessfully Sent"
else
	echo "FILE was Unsuccessful"
fi
