#!/usr/bin/env bash
# Bash script that gives you information about the school file
# Bash script checks if the file exists and print:
# if the file exists: school file exists
# if the file does not exist: school file does not exist
# If the file exists, print:
# if the file is empty: school file is empty
# if the file is not empty: school file is not empty
# if the file is a regular file: school is a regular file
# if the file is not a regular file: (nothing)

file="school"
if [ -e $file ]
then
    echo "$file file exists"
    if [ -f $file ]
    then
        echo "$file is a regular file"
    fi
    if [ -s $file ]
    then 
        echo "$file file is not empty"
    else
        echo "$file file is empty"
    fi
else
    echo "$file file does not exist"
fi
